"""
This type stub file was generated by pyright.
"""

from .validated_entry import ValidatedEntry
from .validators import CapitalizedStringValidator, EmailValidator, IPv4Validator, PasswordValidator

"""
Author: Dogeek
License: GNU GPLv3
Source: This repository

ValidatedEntry widgets for string validation
"""
class LowerStringEntry(ValidatedEntry):
    """
    Validates only lowercase ascii characters.
    """
    VALIDATOR = ...


class UpperStringEntry(ValidatedEntry):
    """
    Validates only uppercase ascii characters.
    """
    VALIDATOR = ...


class CapitalizedStringEntry(ValidatedEntry):
    """
    Validates only capitalized strings (Starts with a capital letter, then any character)
    """
    VALIDATOR = CapitalizedStringValidator


class EmailEntry(ValidatedEntry):
    """
    Validates email addresses.
    """
    VALIDATOR = EmailValidator


class PasswordEntry(ValidatedEntry):
    """
    Validates passwords. The requirements are as follows:
        * At least 1 lowercase character
        * At least 1 uppercase character
        * At least 1 digit
        * At least 1 special character (!@#$%^&*)
        * Be at least 8 characters long
    """
    VALIDATOR = PasswordValidator


class IPv4Entry(ValidatedEntry):
    """
    Validates IPv4 addresses
    """
    VALIDATOR = IPv4Validator


