"""
This type stub file was generated by pyright.
"""

import tkinter.ttk as ttk

"""
Author: Dogeek
License: GNU GPLv3
Source: This repository

ValidatedEntry widget using validators to check the input against specific patterns.
"""
class ValidatedEntry(ttk.Entry):
    """
    ValidatedEntry base class.
    An entry that has a VALIDATOR class attribute.
    Set it to a validator class from `ttkwidgets.validated_entries.validators`

    The entry won't accept input that has not been validated.
    """
    VALIDATOR = ...
    def configure_validator(self, validator=...): # -> None:
        """
        Configures the validator on this entry. See `ValidatedEntry._get_validator`
        for more info.
        """
        ...
    


