"""
This type stub file was generated by pyright.
"""

from tkinter import ttk

"""
Authors: Mitja Martini and Russell Adams
License: "Licensed same as original by Mitja Martini or public domain, whichever is less restrictive"
Source: https://mail.python.org/pipermail/tkinter-discuss/2012-January/003041.html

Edited by RedFantom for ttk and Python 2 and 3 cross-compatibility and <Enter> binding
"""
tk_umlauts = ...
class AutocompleteEntry(ttk.Entry):
    """
    Subclass of :class:`ttk.Entry` that features autocompletion.

    To enable autocompletion use :meth:`set_completion_list` to define
    a list of possible strings to hit.
    To cycle through hits use down and up arrow keys.
    """
    def __init__(self, master=..., completevalues=..., **kwargs) -> None:
        """
        Create an AutocompleteEntry.

        :param master: master widget
        :type master: widget
        :param completevalues: autocompletion values
        :type completevalues: list
        :param kwargs: keyword arguments passed to the :class:`ttk.Entry` initializer
        """
        ...
    
    def set_completion_list(self, completion_list): # -> None:
        """
        Set a new auto completion list

        :param completion_list: completion values
        :type completion_list: list
        """
        ...
    
    def autocomplete(self, delta=...): # -> None:
        """
        Autocomplete the Entry.

        :param delta: 0, 1 or -1: how to cycle through possible hits
        :type delta: int
        """
        ...
    
    def handle_keyrelease(self, event): # -> None:
        """
        Event handler for the keyrelease event on this widget.

        :param event: Tkinter event
        """
        ...
    
    def handle_return(self, event): # -> None:
        """
        Function to bind to the Enter/Return key so if Enter is pressed the selection is cleared.

        :param event: Tkinter event
        """
        ...
    
    def config(self, **kwargs): # -> None:
        """Alias for configure"""
        ...
    
    def configure(self, **kwargs):
        """Configure widget specific keyword arguments in addition to :class:`ttk.Entry` keyword arguments."""
        ...
    
    def cget(self, key): # -> list[Any] | Any | None:
        """Return value for widget specific keyword arguments"""
        ...
    
    def keys(self): # -> list[str]:
        """Return a list of all resource names of this widget."""
        ...
    
    def __setitem__(self, key, value): # -> None:
        ...
    
    def __getitem__(self, item): # -> list[Any] | Any | None:
        ...
    


