"""
This type stub file was generated by pyright.
"""

from tkinter import ttk

"""
Author: Juliette Monsel
License: GNU GPLv3
Source: This repository
"""
class AutocompleteEntryListbox(ttk.Frame):
    """
    :class:`ttk.Entry` that features autocompletion combined with a
    :class:`tk.Listbox` to display the completion list.
    """
    def __init__(self, master=..., completevalues=..., allow_other_values=..., autohidescrollbar=..., **kwargs) -> None:
        """
        Create an Entry + Listbox widget with autocompletion.

        :param master: master widget
        :type master: widget
        :param completevalues: autocompletion values
        :type completevalues: list
        :param allow_other_values: whether the user is allowed to enter values not in the list
        :type allow_other_values: bool
        :param width: widget width (in characters)
        :type width: int
        :param exportselection: whether to automatically export selected text to the clipboard
        :type exportselection: bool
        :param justify: text alignment in entry and listbox
        :type justify: str
        :param font: font in entry and listbox
        :param autohidescrollbar: whether to use an :class:`~ttkwidgets.AutoHideScrollbar` or a :class:`ttk.Scrollbar`
        :type autohidescrollbar: bool
        :param kwargs: keyword arguments passed to the :class:`ttk.Frame` initializer
        """
        ...
    
    def __getitem__(self, key): # -> bool | Any:
        ...
    
    def __setitem__(self, key, value): # -> None:
        ...
    
    def keys(self): # -> list[str]:
        ...
    
    def get(self): # -> str:
        "Return the text in the entry."
        ...
    
    def cget(self, key): # -> bool | Any:
        ...
    
    def configure(self, cnf=..., **kw): # -> None:
        ...
    
    config = ...


