"""
This type stub file was generated by pyright.
"""

import tkinter as tk

"""
Author: RedFantom
License: GNU GPLv3
Source: This repository
"""
class DebugWindow(tk.Toplevel):
    """
    A Toplevel that shows sys.stdout and sys.stderr for Tkinter applications
    """
    def __init__(self, master=..., title=..., stdout=..., stderr=..., width=..., autohidescrollbar=..., **kwargs) -> None:
        """
        Create a Debug window.
        
        :param master: master widget
        :type master: widget
        :param stdout: whether to redirect stdout to the widget
        :type stdout: bool
        :param stderr:  whether to redirect stderr to the widget
        :type stderr: bool
        :param width: window width (in characters)
        :type width: int
        :param autohidescrollbar: whether to use an :class:`~ttkwidgets.AutoHideScrollbar` or a :class:`ttk.Scrollbar`
        :type autohidescrollbar: bool
        :param kwargs: options to be passed on to the :class:`tk.Toplevel` initializer
        """
        ...
    
    def save(self): # -> None:
        """Save widget content."""
        ...
    
    def write(self, line): # -> None:
        """
        Write line at the end of the widget.
        
        :param line: text to insert in the widget
        :type line: str
        """
        ...
    
    def flush(self): # -> None:
        ...
    
    def quit(self): # -> None:
        """Restore previous stdout/stderr and destroy the window."""
        ...
    


