"""
This type stub file was generated by pyright.
"""

from tkinter import ttk

"""
Author: RedFantom
License: GNU GPLv3
Source: This repository
"""
class LinkLabel(ttk.Label):
    """
    A :class:`ttk.Label` that can be clicked to open a link with a default blue color, a purple color when clicked and a bright
    blue color when hovering over the Label.
    """
    def __init__(self, master=..., **kwargs) -> None:
        """
        Create a LinkLabel.
        
        :param master: master widget
        :param link: link to be opened
        :type link: str
        :param normal_color: text color when widget is created
        :type normal_color: str
        :param hover_color: text color when hovering over the widget
        :type hover_color: str
        :param clicked_color: text color when link is clicked
        :type clicked_color: str
        :param kwargs: options to be passed on to the :class:`ttk.Label` initializer
        """
        ...
    
    def __getitem__(self, key): # -> Any:
        ...
    
    def __setitem__(self, key, value): # -> None:
        ...
    
    def reset(self): # -> None:
        """Reset Label to unclicked status if previously clicked."""
        ...
    
    def open_link(self, *args): # -> None:
        """Open the link in the web browser."""
        ...
    
    def cget(self, key): # -> Any:
        """
        Query widget option.

        :param key: option name
        :type key: str
        :return: value of the option

        To get the list of options for this widget, call the method :meth:`~LinkLabel.keys`.
        """
        ...
    
    def configure(self, **kwargs): # -> None:
        """
        Configure resources of the widget.

        To get the list of options for this widget, call the method :meth:`~LinkLabel.keys`.
        See :meth:`~LinkLabel.__init__` for a description of the widget specific option.
        """
        ...
    
    def keys(self): # -> list[str]:
        """Return a list of all resource names of this widget."""
        ...
    


