"""
This type stub file was generated by pyright.
"""

from tkinter import ttk

"""
Author: RedFantom
License: GNU GPLv3
Source: This repository
"""
class ScrolledListbox(ttk.Frame):
    """Simple :class:`tk.Listbox` with an added scrollbar."""
    def __init__(self, master=..., compound=..., autohidescrollbar=..., **kwargs) -> None:
        """
        Create a Listbox with a vertical scrollbar.

        :param master: master widget
        :type master: widget
        :param compound: side for the Scrollbar to be on (:obj:`tk.LEFT` or :obj:`tk.RIGHT`)
        :type compound: str
        :param autohidescrollbar: whether to use an :class:`~ttkwidgets.AutoHideScrollbar` or a :class:`ttk.Scrollbar`
        :type autohidescrollbar: bool
        :param kwargs: keyword arguments passed on to the :class:`tk.Listbox` initializer
        """
        ...
    
    def config_listbox(self, *args, **kwargs): # -> None:
        """Configure resources of the Listbox widget."""
        ...
    


