"""
This type stub file was generated by pyright.
"""

from tkinter import ttk

"""
Author: RedFantom
License: GNU GPLv3
Source: This repository
"""
class TimeLine(ttk.Frame):
    """
    A Frame containing a Canvas and various buttons to manage a timeline
    that can be marked with certain events, allowing the binding of
    commands to hovering over certain elements and creating texts inside
    the elements.

    Each marker is pretty much a coloured rectangle with some optional
    text, that can be assigned tags. Tags may specify the colors of the
    marker, but tags can also be assigned callbacks that can be called
    with the identifier of the tag as well as a Tkinter event instance
    that was generated upon clicking. For example, the markers may be
    moved, or the user may want to add a menu that shows upon
    right-clicking. See the :meth:`create_marker` function for more details on
    the markers.

    The markers are put into a Canvas, which contains rows for each
    category. The categories are indicated by Labels and separated by
    black separating lines. Underneath the rows of categories, there is
    a second Canvas containing markers for the ticks of the time unit.
    Some time units get special treatment, such as "h" and "m",
    displayed in an appropriate H:M and M:S format respectively.

    The height of the row for each category is automatically adjusted to
    the height of its respective Label to give a uniform appearance.
    All markers are redrawn if :meth:`draw_timeline` is called,
    and therefore it should be called after any size change. Depending
    on the number of markers to draw, it may take a long time.

    The TimeLine can be scrolled in two ways: horizontally (with
    :obj:`_scrollbar_timeline`) and vertically (with :obj:`_scrollbar_timeline_v`),
    which both use a class function as a proxy to allow for other
    functions to be called upon scrolling. The horizontal scrollbar
    makes a small pop-up window appear to indicate the time the cursor
    is currently pointing at on the timeline.

    The markers can be retrieved from the class using the markers
    property, and they can be saved and then the markers can be
    recreated by calling :meth:`create_marker` again for each marker. This
    functionality is not built into the class, if the user wants to do
    something like this, he or she should write the code required, as it
    can be done in different ways.

    Some of the code has been inspired by the :class:`ItemsCanvas`, as that is
    also a Canvas that supports the manipulation of items, but as this
    works in a fundamentally different way, the classes do not share any
    common parent class.

    .. warning::
         This widget is *absolutely not* thread-safe, and it was not designed
         as such. It may work in some situations, but nothing is guaranteed
         when using this widget from multiple threads, even with Tkinter
         compiled with thread-safe flags or when using mtTkinter for
         Python 2.

    .. note::
         Some themes may conflict with this widget, for example because it
         makes the default font bigger for the category Labels. This should
         be fixed by the user by modifying the "TimeLine.T(Widget)" style.
    """
    def __init__(self, master=..., **kwargs) -> None:
        """
        Create a TimeLine widget

        The style of the buttons can be modified by using the
        "TimeLine.TButton" style.
        The style of the surrounding Frame can be modified by using the
        "TimeLine.TFrame" style, or by specifying another style in the
        keyword arguments.
        The style of the category Labels can be modified by using the
        "TimeLine.TLabel" style.

        **Base TimeLine Widget Options**

        :param width: Width of the timeline in pixels
        :type width: int
        :param height: Height of the timeline in pixels
        :type height: int
        :param extend: Whether to extend when an item is moved out of
            range
        :type extend: bool
        :param start: Value to start the timeline at
        :type start: float
        :param finish: Value to end the timeline at
        :type finish: float
        :param resolution: Amount of time per pixel [s/pixel]
        :type resolution: int
        :param tick_resolution: Amount of time between ticks on the
            timeline
        :type tick_resolution: int
        :param unit: Unit of time. Some units have predefined
            properties, such as minutes ('m') and hours ('h'), which
            make the tick markers have an appropriate format.
        :type unit: str
        :param zoom_enabled: Whether to allow zooming on the timeline
            using the zoom buttons
        :type zoom_enabled: bool
        :param categories: A dictionary with the names of the categories
            as the keys and the keyword argument dictionaries as values.
            Use an :obj:`OrderedDict` in order to preserve category
            order.
        :type categories: dict[Any, dict]
        :param background: Background color for the Canvas widget
        :type background: str
        :param style: Style to apply to the Frame widget
        :type style: str
        :param zoom_factors: Tuple of allowed zoom levels. For example:
            (1.0, 2.0, 5.0). The order of zoom levels is preserved.
        :type zoom_factors: tuple[float]
        :param zoom_default: Default zoom level to apply to the timeline
        :type zoom_default: float
        :param snap_margin: Amount of pixels between start and/or finish
            of a marker and a tick on the timeline before the marker is
            snapped into place
        :type snap_margin: int
        :param menu: Menu to show when a right-click is performed
            somewhere on the TimeLine without a marker being active
        :type menu: tk.Menu
        :param autohidescrollbars: whether to use :class:`~ttkwidgets.AutoHideScrollbar`
            or :class:`ttk.Scrollbar` for the scrollbars
        :type autohidescrollbars: bool

        **Marker Default Options**

        :param marker_font: Font tuple to specify the default font for
            the markers
        :type marker_font: tuple
        :param marker_background: Default background color for markers
        :type marker_background: str
        :param marker_foreground: Default foreground color for markers
        :type marker_foreground: str
        :param marker_outline: Default outline color for the markers
        :type marker_outline: str
        :param marker_border: Border width in pixels
        :type marker_border: int
        :param marker_move: Whether markers are allowed to move by
            default
        :type marker_move: bool
        :param marker_change_category: Whether markers are allowed to
            change category by being dragged vertically
        :type marker_change_category: bool
        :param marker_allow_overlap: Whether the markers are allowed to
            overlap. This setting is only enforced on the marker being
            moved. This means that when inserting markers, no errors
            will be raised, even with overlaps, and when an
            overlap-allowing marker is moved over an overlap-disallowing
            marker and overlap will still occur.
        :type marker_allow_overlap: bool
        :param marker_snap_to_ticks: Whether the markers should snap to
            the ticks when moved close to ticks automatically
        """
        ...
    
    def grid_widgets(self): # -> None:
        """
        Configure all widgets using the grid geometry manager

        Automatically called by the :meth:`__init__` method.
        Does not have to be called by the user except in extraordinary
        cases.
        """
        ...
    
    def draw_timeline(self): # -> None:
        """Draw the contents of the whole TimeLine Canvas"""
        ...
    
    def draw_time_marker(self): # -> None:
        """Draw the time marker on the TimeLine Canvas"""
        ...
    
    def draw_categories(self): # -> None:
        """Draw the category labels on the Canvas"""
        ...
    
    def create_scroll_region(self): # -> None:
        """Setup the scroll region on the Canvas"""
        ...
    
    def clear_timeline(self): # -> None:
        """
        Clear the contents of the TimeLine Canvas

        Does not modify the actual markers dictionary and thus after
        redrawing all markers are visible again.
        """
        ...
    
    def draw_ticks(self): # -> None:
        """Draw the time tick markers on the TimeLine Canvas"""
        ...
    
    def draw_separators(self): # -> None:
        """Draw the lines separating the categories on the Canvas"""
        ...
    
    def draw_markers(self): # -> None:
        """Draw all created markers on the TimeLine Canvas"""
        ...
    
    def create_marker(self, category, start, finish, marker=..., **kwargs):
        """
        Create a new marker in the TimeLine with the specified options

        :param category: Category identifier, key as given in categories
            dictionary upon initialization
        :type category: Any
        :param start: Start time for the marker
        :type start: float
        :param finish: Finish time for the marker
        :type finish: float
        :param marker: marker dictionary (replaces kwargs)
        :type marker: dict[str, Any]

        **Marker Options**
        
        Options can be given either in the marker dictionary argument,
        or as keyword arguments. Given keyword arguments take precedence
        over tag options, which take precedence over default options.

        :param text: Text to show in the marker. Text may not be
            displayed fully if the zoom level does not allow the marker
            to be wide enough. Updates when resizing the marker.
        :type text: str
        :param background: Background color for the marker
        :type background: str
        :param foreground: Foreground (text) color for the marker
        :type foreground: str
        :param outline: Outline color for the marker
        :type outline: str
        :param border: The width of the border (for which outline is the
            color)
        :type border: int
        :param font: Font tuple to set for the marker
        :type font: tuple
        :param iid: Unique marker identifier to use. A marker is
            generated if not given, and its value is returned. Use this
            option if keeping track of markers in a different manner
            than with auto-generated iid's is necessary.
        :type iid: str
        :param tags: Set of tags to apply to this marker, allowing
            callbacks to be set and other options to be configured. The
            option precedence is from the first to the last item, so
            the options of the last item overwrite those of the one
            before, and those of the one before that, and so on.
        :type tags: tuple[str]
        :param move: Whether the marker is allowed to be moved
        :type move: bool

        Additionally, all the options with the ``marker_`` prefix from
        :meth:`__init__`, but without the prefix, are supported. Active state
        options are also available, with the ``active_`` prefix for
        ``background``, ``foreground``, ``outline``, ``border``. These
        options are also available for the hover state with the
        ``hover_`` prefix.

        :return: identifier of the created marker
        :rtype: str
        :raise ValueError: One of the specified arguments is invalid
        """
        ...
    
    def update_marker(self, iid, **kwargs):
        """
        Change the options for a certain marker and redraw the marker

        :param iid: identifier of the marker to change
        :type iid: str
        :param kwargs: Dictionary of options to update
        :type kwargs: dict
        :raises: ValueError
        """
        ...
    
    def delete_marker(self, iid): # -> None:
        """
        Delete a marker from the TimeLine

        :param iid: marker identifier
        :type iid: str
        """
        ...
    
    def zoom_in(self): # -> None:
        """Increase zoom factor and redraw TimeLine"""
        ...
    
    def zoom_out(self): # -> None:
        """Decrease zoom factor and redraw TimeLine"""
        ...
    
    def zoom_reset(self): # -> None:
        """Reset the zoom factor to default and redraw TimeLine"""
        ...
    
    def set_zoom_factor(self, factor): # -> None:
        """
        Manually set a custom zoom factor

        :param factor: Custom zoom factor
        :type factor: float
        """
        ...
    
    def set_time(self, time): # -> None:
        """
        Set the time marker to a specific time

        :param time: Time to set for the time marker on the TimeLine
        :type time: float
        """
        ...
    
    def tag_configure(self, tag_name, **kwargs): # -> None:
        """
        Create a marker tag

        :param tag_name: Identifier for the tag

        :param move_callback: Callback to be called upon moving a
            marker. Arguments to callback:
            ``(iid: str, (old_start: float, old_finish: float),
            (new_start: float, new_finish: float))``
        :type move_callback: callable
        :param left_callback: Callback to be called upon left clicking
            a marker. Arguments to callback:
            ``(iid: str, x_coord: int, y_coord: int)``
        :type left_callback: callable
        :param right_callback: Callback to be called upon right clicking
            a marker. Arguments to callback:
            ``(iid: str, x_coord: int, y_coord: int)``
        :type right_callback: callable
        :param menu: A Menu widget to show upon right click. Can be
            used with the right_callback option simultaneously.
        :type menu: tk.Menu

        In addition, supports all options supported by markers. Note
        that tag options are applied to markers upon marker creation,
        and thus is a tag is updated, the markers are not automatically
        updated as well.
        """
        ...
    
    def marker_tags(self, iid): # -> Generator[Any, Any, None]:
        """Generator for all the tags of a certain marker"""
        ...
    
    def get_time_position(self, time):
        """
        Get x-coordinate for given time

        :param time: Time to determine x-coordinate on Canvas for
        :type time: float
        :return: X-coordinate for the given time
        :rtype: int
        :raises: ValueError
        """
        ...
    
    def get_position_time(self, position):
        """
        Get time for x-coordinate

        :param position: X-coordinate position to determine time for
        :type position: int
        :return: Time for the given x-coordinate
        :rtype: float
        """
        ...
    
    @staticmethod
    def get_time_string(time, unit): # -> LiteralString | str:
        """
        Create a properly formatted string given a time and unit

        :param time: Time to format
        :type time: float
        :param unit: Unit to apply format of. Only supports hours ('h')
            and minutes ('m').
        :type unit: str
        :return: A string in format '{whole}:{part}'
        :rtype: str
        """
        ...
    
    def update_state(self, iid, state): # -> None:
        """
        Set a custom state of the marker

        :param iid: identifier of the marker to set the state of
        :type iid: str
        :param state: supports "active", "hover", "normal"
        :type state: str
        """
        ...
    
    def update_active(self): # -> None:
        """Update the active marker on the marker Canvas"""
        ...
    
    def call_callbacks(self, iid, type, args): # -> int:
        """
        Call the available callbacks for a certain marker

        :param iid: marker identifier
        :type iid: str
        :param type: type of callback (key in tag dictionary)
        :type type: str
        :param args: arguments for the callback
        :type args: tuple
        :return: amount of callbacks called
        :rtype: int
        """
        ...
    
    @property
    def time(self):
        """
        Current value the time marker is pointing to

        :rtype: float
        """
        ...
    
    @property
    def active(self): # -> None:
        """
        Currently selected marker

        :rtype: str
        """
        ...
    
    @property
    def current(self): # -> int | None:
        """
        Currently active item on the _timeline Canvas

        :rtype: str
        """
        ...
    
    @property
    def current_iid(self): # -> None:
        """
        Currently active item's iid

        :rtype: str
        """
        ...
    
    @property
    def markers(self): # -> dict[Any, Any]:
        """
        Return a dictionary with categories as keys

        :rtype: dict[str, dict[str, Any]]
        """
        ...
    
    @property
    def zoom_factor(self):
        """
        Return the current zoom factor

        :rtype: float
        """
        ...
    
    @property
    def pixel_width(self):
        """
        Width of the whole TimeLine in pixels

        :rtype: int
        """
        ...
    
    @property
    def options(self): # -> list[str]:
        """List of available options to :meth:`__init__`"""
        ...
    
    @property
    def marker_options(self): # -> list[str]:
        """List of available options to create_marker"""
        ...
    
    def configure(self, cnf=..., **kwargs): # -> None:
        """Update options of the TimeLine widget"""
        ...
    
    config = ...
    def cget(self, item): # -> Any:
        """Return the value of an option"""
        ...
    
    def __getitem__(self, item): # -> Any:
        ...
    
    def __setitem__(self, key, value): # -> None:
        ...
    
    def itemconfigure(self, iid, rectangle_options, text_options): # -> None:
        """
        Configure options of items drawn on the Canvas

        Low-level access to the individual elements of markers and other
        items drawn on the timeline Canvas. All modifications are
        overwritten when the TimeLine is redrawn.
        """
        ...
    
    @staticmethod
    def calculate_text_coords(rectangle_coords): # -> tuple[int, int]:
        """Calculate Canvas text coordinates based on rectangle coords"""
        ...
    
    @staticmethod
    def range(start, finish, step): # -> Generator[Any, Any, None]:
        """Like built-in :func:`~builtins.range`, but with float support"""
        ...
    
    @staticmethod
    def check_kwargs(kwargs): # -> None:
        """
        Check the type and values of keyword arguments to :meth:`__init__`

        :param kwargs: Dictionary of keyword arguments
        :type kwargs: dict[str, Any]
        :raises: TypeError, ValueError
        """
        ...
    
    def check_marker_kwargs(self, kwargs): # -> None:
        """
        Check the types of the keyword arguments for marker creation

        :param kwargs: dictionary of options for marker creation
        :type kwargs: dict
        :raises: TypeError, ValueError
        """
        ...
    


