"""
This type stub file was generated by pyright.
"""

"""
Author: The ttkwidgets authors
License: GNU GPLv3
Source: The ttkwidgets repository
"""
def get_assets_directory(): # -> str:
    ...

def open_icon(icon_name): # -> PhotoImage:
    ...

def isfloat(value): # -> bool:
    """
    Checks if a value is a float
    :param value: any variable
    :returns: True if value is a float, string matching \d+\.\d* or tk.FloatVar
    """
    ...

def isint(value): # -> bool:
    """
    Checks if a value is an int
    :param value: any variable
    :returns: True if value is an int, string matching \d+ or tk.IntVar
    """
    ...

def parse_geometry_string(string): # -> tuple[int, int, int, int]:
    """Parse a Tkinter geometry string ('XxY+W+H') into a box tuple"""
    ...

